apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myapp-rs
    labels:
        tier: front-end
spec: 
   selector:
     matchLabels:
       tier: production
         
   template:
      metadata:
        name: myapp-pod
        labels:
           name: pod
           tier: production
      spec:
         containers:
           - name: nginx
             image: nginx
   replicas: 3
